name: Build

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v2
        with:
          node-version: '17'

      - run: npm install

      - name: ncc build
        run: |
          npx @vercel/ncc build src/main.ts --license licenses.txt

      - name: commit
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "action@github.com"
          git add dist/main.d.ts dist/licenses.txt dist/index.js
          git commit -a -m 'commit dist'
          git push origin HEAD:main
