name: Build

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v1
      - uses: tool3/ncc@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          src: 'src/main.ts'
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
