name: Build

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v1

      - name: ncc build
        run: |
          ncc build src/main.ts --license licenses.txt
